In [11]:
import pandas as pd
import duckdb

In [12]:
duckdb.sql('SET enable_progress_bar = true')

In [13]:
# Load the data
duckdb.sql('''
           select
             *
           from '../../data/taxi_trips.csv'
           limit 10
           '''
).df().T

,0,1,2,3,4,5,6,7,8,9
VendorID,2,2,2,2,2,1,1,2,2,2
tpep_pickup_datetime,2018-07-17 10:14:57,2018-07-17 10:23:50,2018-07-17 10:39:57,2018-07-17 10:12:58,2018-07-17 10:24:49,2018-07-17 10:29:59,2018-07-17 10:44:55,2018-07-17 10:02:58,2018-07-17 10:23:14,2018-07-17 10:01:52
tpep_dropoff_datetime,2018-07-17 10:22:45,2018-07-17 10:37:49,2018-07-17 11:07:52,2018-07-17 10:22:47,2018-07-17 10:48:37,2018-07-17 10:41:50,2018-07-17 10:59:11,2018-07-17 10:31:42,2018-07-17 10:50:12,2018-07-17 10:06:29
passenger_count,2,2,2,1,1,1,1,1,5,1
trip_distance,1.0,1.24,5.12,0.88,2.07,1.2,1.3,4.03,2.31,0.63
RatecodeID,1,1,1,1,1,1,1,1,1,1
store_and_fwd_flag,N,N,N,N,N,N,N,N,N,N
PULocationID,186,234,186,48,186,50,48,246,237,230
DOLocationID,234,186,88,186,163,100,186,209,233,163
payment_type,1,1,1,2,1,1,2,1,1,1
fare_amount,7.0,9.5,22.0,7.5,15.0,8.5,10.0,20.5,16.5,5.0
extra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mta_tax,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
tip_amount,2.34,1.03,2.0,0.0,0.79,1.85,0.0,4.26,2.0,1.16
tolls_amount,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
improvement_surcharge,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3
total_amount,10.14,11.33,24.8,8.3,16.59,11.15,10.8,25.56,19.3,6.96

In [14]:
def qw(query):
    """
    Helper function to execute a query and return the result as a DataFrame.
    """
    with duckdb.connect('../../taxi_data.duckdb') as con:
        return con.execute(query).fetchdf()
    with duckdb.connect('../../taxi_data.duckdb') as con:
        df = con.execute(query).fetchdf()

    return df

In [15]:
qw('''
SELECT * FROM dbt_models.mart_trip_summary
''')

    summary_type  total_trips
0  daily_summary    111411378

In [16]:
qw('''
SELECT * FROM dbt_models.payment_types
''')

   id         name
0   1  Credit card
1   2         Cash
2   3    No charge
3   4      Dispute
4   5      Unknown
5   6  Voided trip

In [17]:
qw('''
SELECT * FROM dbt_models.payment_types
''')

   id         name
0   1  Credit card
1   2         Cash
2   3    No charge
3   4      Dispute
4   5      Unknown
5   6  Voided trip

In [18]:
qw('''
SELECT *
FROM dbt_models.ratecodes
''')

   id                   name
0   1          Standard rate
1   2                    JFK
2   3                 Newark
3   4  Nassau or Westchester
4   5        Negotiated fare
5   6             Group ride

In [24]:
qw('SELECT * FROM information_schema.tables')

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action,TABLE_COMMENT
0,taxi_data,dbt_models,mart_trip_summary,BASE TABLE,None,None,None,None,None,YES,NO,None,None
1,taxi_data,dbt_models,payment_types,BASE TABLE,None,None,None,None,None,YES,NO,None,None
2,taxi_data,dbt_models,ratecodes,BASE TABLE,None,None,None,None,None,YES,NO,None,None
3,taxi_data,main,taxi_trips,BASE TABLE,None,None,None,None,None,YES,NO,None,None
4,taxi_data,dbt_models,stg_taxi_trips,VIEW,None,None,None,None,None,NO,NO,None,None

In [32]:
qw('''
   SELECT
     taxi_trips.pickup_datetime,
     taxi_trips.trip_distance,
     ratecodes.name AS rate_code_name,
     payment_types.name AS payment_type_name
   FROM dbt_models.stg_taxi_trips AS taxi_trips
   LEFT JOIN dbt_models.ratecodes AS ratecodes
          ON taxi_trips.rate_code_id = ratecodes.id
   LEFT JOIN dbt_models.payment_types AS payment_types
          ON taxi_trips.payment_type = payment_types.id
   LIMIT 10
   ''')

      pickup_datetime  trip_distance rate_code_name payment_type_name
0 2018-07-17 18:47:15           1.60  Standard rate              Cash
1 2018-07-17 18:02:51           0.78  Standard rate       Credit card
2 2018-07-17 18:12:11           0.43  Standard rate              Cash
3 2018-07-17 18:17:28           2.06  Standard rate       Credit card
4 2018-07-17 18:30:14           1.43  Standard rate              Cash
5 2018-07-17 18:42:16           2.15  Standard rate              Cash
6 2018-07-17 18:34:31           6.00  Standard rate       Credit card
7 2018-07-17 18:19:59           0.90  Standard rate       Credit card
8 2018-07-17 18:31:52           2.40  Standard rate       Credit card
9 2018-07-17 18:55:43           1.10  Standard rate       Credit card